PALETTES = {
    "midnight": {
        "label": "Midnight",
        "dark": True,
        "bg": "#0f1115",
        "surface": "#1a1d24",
        "border": "#2a2e37",
        "text": "#e8e9ec",
        "muted": "#8b8f9a",
        "accent": "#5b8cff",
        "success": "#34d399",
        "error": "#f87171",
        "warning": "#fbbf24",
        "diff_add": "#4caf50",
        "diff_remove": "#f44336",
        "diff_modified": "#ff9800",
    },
    "forest": {
        "label": "Forest",
        "dark": True,
        "bg": "#0f1512",
        "surface": "#182420",
        "border": "#2a3a33",
        "text": "#e6ece9",
        "muted": "#8fa89c",
        "accent": "#4ade80",
        "success": "#34d399",
        "error": "#f87171",
        "warning": "#fbbf24",
        "diff_add": "#4ade80",
        "diff_remove": "#f87171",
        "diff_modified": "#facc15",
    },
    "sunset": {
        "label": "Sunset",
        "dark": True,
        "bg": "#160f13",
        "surface": "#241a20",
        "border": "#3a2a33",
        "text": "#f0e6ea",
        "muted": "#a88f9c",
        "accent": "#fb7185",
        "success": "#34d399",
        "error": "#f87171",
        "warning": "#fb923c",
        "diff_add": "#fb923c",
        "diff_remove": "#fb7185",
        "diff_modified": "#facc15",
    },
    "daylight": {
        "label": "Daylight",
        "dark": False,
        "bg": "#f7f8fa",
        "surface": "#ffffff",
        "border": "#e2e5ea",
        "text": "#1a1d24",
        "muted": "#6b7280",
        "accent": "#3b6fe0",
        "success": "#16a34a",
        "error": "#dc2626",
        "warning": "#d97706",
        "diff_add": "#16a34a",
        "diff_remove": "#dc2626",
        "diff_modified": "#d97706",
    },
    "paper": {
        "label": "Paper",
        "dark": False,
        "bg": "#faf6f0",
        "surface": "#ffffff",
        "border": "#e8dfd2",
        "text": "#2b2621",
        "muted": "#8a8073",
        "accent": "#b5651d",
        "success": "#4d7c0f",
        "error": "#b91c1c",
        "warning": "#b45309",
        "diff_add": "#4d7c0f",
        "diff_remove": "#b91c1c",
        "diff_modified": "#b45309",
    },
}

DEFAULT_PALETTE = "midnight"


def get_palette(name: str) -> dict:
    return PALETTES.get(name, PALETTES[DEFAULT_PALETTE])
